import {
  IsString,
  IsEnum,
  IsInt,
  IsDateString,
  IsOptional,
  IsEmail,
  IsBoolean,
  IsArray,
  Min,
  IsNotEmpty,
  ValidateIf,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  EmploymentType,
  TeacherStatus,
  TeacherRole,
  Gender,
  HighestQualification,
} from '../enums/teacher.enum';

export class CreateTeacherDto {
  // ── Personal Information ──────────────────────────────────────────────────
  // Note: teacherId (Teacher ID / Employee Number) is auto-generated by the
  // server on creation and must not be supplied by the client.

  @ApiProperty({ description: 'First name of the teacher', example: 'Sarah' })
  @IsString()
  @IsNotEmpty()
  firstName!: string;

  @ApiPropertyOptional({ description: 'Middle name (optional)', example: 'Grace' })
  @IsOptional()
  @IsString()
  middleName?: string;

  @ApiProperty({ description: 'Last name of the teacher', example: 'Namukasa' })
  @IsString()
  @IsNotEmpty()
  lastName!: string;

  @ApiProperty({ description: 'Gender of the teacher', enum: Gender, example: Gender.FEMALE })
  @IsEnum(Gender)
  gender!: Gender;

  @ApiProperty({ description: 'Date of birth (YYYY-MM-DD)', example: '1990-06-15' })
  @IsDateString()
  dateOfBirth!: string;

  @ApiPropertyOptional({ description: 'Nationality of the teacher', example: 'Ugandan' })
  @IsOptional()
  @IsString()
  nationality?: string;

  @ApiProperty({ description: 'Phone number', example: '+256701234567' })
  @IsString()
  @IsNotEmpty()
  phoneNumber!: string;

  @ApiProperty({ description: 'Email address (must be unique)', example: 'sarah.namukasa@school.ac.ug' })
  @IsEmail()
  email!: string;

  @ApiProperty({ description: 'Physical / residential address', example: 'Kampala, Nakawa Division' })
  @IsString()
  @IsNotEmpty()
  physicalAddress!: string;

  // ── Employment Information ────────────────────────────────────────────────

  @ApiProperty({
    description: 'Type of employment contract',
    enum: EmploymentType,
    example: EmploymentType.FULL_TIME,
  })
  @IsEnum(EmploymentType)
  employmentType!: EmploymentType;

  @ApiProperty({ description: 'Date the teacher joined the school (YYYY-MM-DD)', example: '2020-02-01' })
  @IsDateString()
  dateOfJoining!: string;

  @ApiProperty({ description: 'Department the teacher belongs to', example: 'Sciences' })
  @IsString()
  @IsNotEmpty()
  department!: string;

  @ApiProperty({ description: 'Job title or designation', example: 'Senior Teacher' })
  @IsString()
  @IsNotEmpty()
  designation!: string;

  @ApiPropertyOptional({
    description: 'Current employment status (defaults to Active)',
    enum: TeacherStatus,
    example: TeacherStatus.ACTIVE,
  })
  @IsOptional()
  @IsEnum(TeacherStatus)
  status?: TeacherStatus;

  // ── Academic Information ──────────────────────────────────────────────────

  @ApiProperty({
    description: 'Highest academic qualification attained',
    enum: HighestQualification,
    example: HighestQualification.BACHELORS,
  })
  @IsEnum(HighestQualification)
  highestQualification!: HighestQualification;

  @ApiProperty({ description: 'University or institution attended', example: 'Makerere University' })
  @IsString()
  @IsNotEmpty()
  institution!: string;

  @ApiPropertyOptional({ description: 'Subject area or specialization (optional)', example: 'Mathematics Education' })
  @IsOptional()
  @IsString()
  specialization?: string;

  @ApiPropertyOptional({ description: 'Total years of teaching experience (optional)', example: 8, minimum: 0 })
  @IsOptional()
  @IsInt()
  @Min(0)
  yearsOfExperience?: number;

  @ApiPropertyOptional({
    description: 'Any professional certifications (comma-separated or descriptive, optional)',
    example: 'TESOL, Special Needs Education',
  })
  @IsOptional()
  @IsString()
  certifications?: string;

  // ── Teaching Information ──────────────────────────────────────────────────

  @ApiProperty({
    description: 'List of subjects the teacher teaches',
    example: ['Mathematics', 'Physics'],
    type: [String],
  })
  @IsArray()
  @IsString({ each: true })
  subjectsTaught!: string[];

  @ApiPropertyOptional({
    description: 'List of classes assigned to the teacher (optional)',
    example: ['Senior Four', 'Senior Five'],
    type: [String],
  })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  assignedClasses?: string[];

  @ApiPropertyOptional({
    description: 'List of streams assigned to the teacher (optional)',
    example: ['Alpha', 'Beta'],
    type: [String],
  })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  assignedStreams?: string[];

  @ApiProperty({
    description: 'Whether this teacher is a class teacher (true/false)',
    example: false,
  })
  @IsBoolean()
  isClassTeacher!: boolean;

  // ── Emergency Contact ─────────────────────────────────────────────────────

  @ApiProperty({ description: 'Full name of the emergency contact person', example: 'John Namukasa' })
  @IsString()
  @IsNotEmpty()
  emergencyContactName!: string;

  @ApiProperty({ description: 'Relationship to the teacher', example: 'Spouse' })
  @IsString()
  @IsNotEmpty()
  emergencyContactRelationship!: string;

  @ApiProperty({ description: 'Phone number of the emergency contact', example: '+256789876543' })
  @IsString()
  @IsNotEmpty()
  emergencyContactPhone!: string;

  @ApiPropertyOptional({ description: 'Address of the emergency contact (optional)', example: 'Kampala, Ntinda' })
  @IsOptional()
  @IsString()
  emergencyContactAddress?: string;

  // ── System Information ────────────────────────────────────────────────────

  @ApiPropertyOptional({
    description: 'Whether to create a login account for this teacher (defaults to false)',
    example: true,
  })
  @IsOptional()
  @IsBoolean()
  createLoginAccount?: boolean;

  @ApiPropertyOptional({
    description: 'Login username (required and must be unique when createLoginAccount is true)',
    example: 'sarah.namukasa',
  })
  @ValidateIf((dto) => dto.createLoginAccount === true)
  @IsString()
  @IsNotEmpty()
  username?: string;

  @ApiPropertyOptional({
    description: 'Login password (required when createLoginAccount is true; will be hashed before storage)',
    example: 'Str0ngP@ss!',
  })
  @ValidateIf((dto) => dto.createLoginAccount === true)
  @IsString()
  @IsNotEmpty()
  password?: string;

  @ApiPropertyOptional({
    description: 'System role assigned to the teacher (defaults to Teacher)',
    enum: TeacherRole,
    example: TeacherRole.TEACHER,
  })
  @IsOptional()
  @IsEnum(TeacherRole)
  role?: TeacherRole;
}
